import { PrismaClient, PlatformName, Priority } from '@prisma/client';
import { requirements, checklist, documents, costs, articles } from '../lib/data';
const prisma = new PrismaClient();
const map=(p:string): PlatformName => ({'All':'ALL','Mr D':'MR_D','Bolt':'BOLT','Uber Eats':'UBER_EATS','Uber passengers':'UBER_PASSENGERS'}[p] as PlatformName);
async function main(){
 await prisma.user.upsert({where:{email:'owner@example.com'},update:{},create:{name:'Demo Sole Proprietor',email:'owner@example.com'}});
 for (const [name,items] of Object.entries(requirements)){const platform=await prisma.platform.upsert({where:{name:map(name)},update:{displayName:name},create:{name:map(name),displayName:name,applicationTypes:name.includes('passengers')||name==='Bolt'?['Passenger transport','Package delivery']:['Food delivery','Grocery delivery','Package delivery']}}); await prisma.platformRequirement.deleteMany({where:{platformId:platform.id}}); for (const item of items){const [title,...rest]=item.split(':'); await prisma.platformRequirement.create({data:{platformId:platform.id,category:title,title,value:rest.join(':').trim()||item,editable:true,notes:'Editable because platform rules can change.'}})}}
 await prisma.startupChecklistItem.deleteMany(); for (const [title,phase,platform,priority,doc,cost] of checklist){await prisma.startupChecklistItem.create({data:{title,description:`Complete this step for ${phase}. Verify current requirements before acting.`,phase,platform:map(platform),priority:priority.toUpperCase() as Priority,documentRequired:doc,estimatedCost:cost,notes:phase.includes('Business')?'Sole proprietors do not register with CIPC by default; verify VAT and SARS requirements directly with SARS.':undefined}})}
 await prisma.requiredDocument.deleteMany(); for (const d of documents){await prisma.requiredDocument.create({data:{documentName:d,category:d.includes('Vehicle')||d.includes('roadworthy')?'Vehicle':d.includes('SARS')||d.includes('tax')?'Tax':'Identity and platform',platform:'ALL',requiredFor:'Platform onboarding and business readiness',status:'MISSING',notes:'Check expiry and platform upload format.'}})}
 await prisma.startupCost.deleteMany(); for (const [i,c] of costs.entries()){await prisma.startupCost.create({data:{itemName:c,category:i<2?'Permits':i<3?'Insurance':i<4?'Smartphone':i<8?'Equipment':'Vehicle inspection',estimatedCost:[300,700,1200,3500,250,450,180,350,650,1000][i],platform:'ALL',paymentStatus:'NOT_PAID'}})}
 await prisma.vehiclePlan.deleteMany(); await prisma.vehiclePlan.create({data:{vehicleType:'4-door sedan or light delivery vehicle',ownershipType:'PLANNING_TO_BUY',vehicleYear:2013,platformUse:'ALL',monthlyRepaymentOrRentalCost:4500,estimatedMonthlyFuelCost:3500,insuranceCost:1200,maintenanceEstimate:800,licenceStatus:'Missing',roadworthyStatus:'Missing',inspectionStatus:'Not booked',operatingCardStatus:'Check if required',notes:'Readiness score improves when licence, roadworthy, inspection, and operating card statuses are ready.'}});
 await prisma.platformApplication.deleteMany(); for (const p of ['MR_D','BOLT','UBER_EATS','UBER_PASSENGERS'] as PlatformName[]){await prisma.platformApplication.create({data:{platform:p,applicationType:p==='UBER_PASSENGERS'||p==='BOLT'?'PASSENGER_TRANSPORT':'FOOD_DELIVERY',applicationStatus:'DOCUMENTS_GATHERING',dateStarted:new Date(),notes:'Readiness depends on documents, vehicle, and permit status.'}})}
 await prisma.weeklyIncome.deleteMany(); await prisma.weeklyExpense.deleteMany(); await prisma.weeklyIncome.create({data:{platform:'UBER_EATS',date:new Date(),shiftType:'DINNER',grossIncome:650,tips:40,tripsOrDeliveries:12,notes:'Demo shift'}}); await prisma.weeklyExpense.create({data:{date:new Date(),category:'FUEL',amount:220,platform:'ALL',notes:'Demo expense'}});
 await prisma.learningGuideArticle.deleteMany(); for (const [i,title] of articles.entries()){await prisma.learningGuideArticle.create({data:{title,slug:title.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,''),topic:title,order:i,content:`${title}. Practical South African guide: treat platform work like a small business, keep records, compare costs and earnings, protect safety and ratings, and verify current SARS, municipal, permit, vehicle, and platform requirements before applying.`}})}
}
main().finally(()=>prisma.$disconnect());
