export const platforms=['All','Mr D','Bolt','Uber Eats','Uber passengers'] as const;
export const phases=['Business Registration as Sole Proprietor','Driver Licence and Permits','Vehicle Requirements','Platform Registration','Tax and Record Keeping','Equipment Checklist','Multi-App Strategy'];
export const disclaimer='This tracker is educational planning support, not legal, tax, municipal, transport, or platform advice. Platform requirements, SARS rules, municipal rules, permit rules, and vehicle requirements can change. Verify directly with SARS, your municipality or traffic department, and each platform before applying.';
export const requirements={
'Mr D':['Minimum age: 18 years','Driver licence: Valid South African licence','Vehicle type: Motorbike or light vehicle','Smartphone: Android V6 or newer','Background check: Clear criminal record or background check','Vehicle documents: RC1 or certificate of registration, roadworthy certificate','Typical documents: ID or passport, driver licence, proof of address, vehicle RC1, roadworthy certificate, bank details'],
'Bolt':['Minimum age: 18+','Driver licence: Valid South African licence and PrDP for passengers','Vehicle: 4-door vehicle, air conditioning, suitable luggage space','Vehicle year: 2010 or newer in Cape Town, 2013 or newer generally','Smartphone: Android V6 or newer or iOS 8 or newer','Criminal record: Clean criminal record','Special permits: PrDP','Vehicle documents: Operating card or double disc, certificate of roadworthiness, insurance, vehicle registration documents','Additional check: Fingerprint results through PostNet or Jetliner'],
'Uber Eats':['Minimum age: 18+','Driver licence: Valid South African licence depending on vehicle type','Vehicle type: Car, motorbike, or bicycle depending on city and platform rules','Smartphone: Smartphone required','Screening: Background or screening check','Documents: ID, profile photo, driver licence, vehicle documents, bank details'],
'Uber passengers':['Minimum age: 21 years','Driver licence: Professional licence or valid driving licence for required period','PrDP or PDP: Required','Vehicle: 4-door sedan or qualifying vehicle','Vehicle year: 2008 or newer for UberX, but editable','Screening: Screening check at PostNet','Vehicle documents: Operating card, inspection certificate, insurance, operating licence application where applicable','DEKRA inspection: Required in some cities such as Cape Town']
};
export const checklist=[
['Register with SARS for income tax','Business Registration as Sole Proprietor','All','High',true,0],['Register for provisional tax','Business Registration as Sole Proprietor','All','High',true,0],['Open a separate bank account for business income','Business Registration as Sole Proprietor','All','Medium',true,150],['Decide on trading name','Business Registration as Sole Proprietor','All','Low',false,0],['Check whether a municipal trading licence is required','Business Registration as Sole Proprietor','All','High',true,0],['Check VAT registration threshold with SARS','Business Registration as Sole Proprietor','All','Medium',false,0],['Set up record keeping for income and expenses','Business Registration as Sole Proprietor','All','High',false,250],
['Confirm valid South African driver licence','Driver Licence and Permits','All','High',true,0],['Apply for PrDP at traffic department','Driver Licence and Permits','Bolt','High',true,300],['Complete fingerprints for Bolt where required','Driver Licence and Permits','Bolt','High',true,150],['Complete Uber screening at PostNet','Driver Licence and Permits','Uber passengers','High',true,150],['Book driving evaluation if required in the city','Driver Licence and Permits','Uber passengers','Medium',false,0],['Upload permit documents to platforms','Driver Licence and Permits','All','High',true,0],
['Confirm vehicle type','Vehicle Requirements','All','High',false,0],['Confirm vehicle year','Vehicle Requirements','All','High',false,0],['Get vehicle licence disc','Vehicle Requirements','All','High',true,850],['Get vehicle certificate of registration or RC1','Vehicle Requirements','All','High',true,0],['Get valid roadworthy certificate','Vehicle Requirements','All','High',true,700],['Get comprehensive insurance where required','Vehicle Requirements','All','High',true,1200],['Book DEKRA or platform-approved inspection','Vehicle Requirements','Uber passengers','Medium',true,650],['Check operating card or double disc requirements','Vehicle Requirements','Bolt','High',true,0],
['Register on Mr D','Platform Registration','Mr D','Medium',false,0],['Register on Bolt','Platform Registration','Bolt','Medium',false,0],['Register on Uber Eats','Platform Registration','Uber Eats','Medium',false,0],['Register on Uber passengers','Platform Registration','Uber passengers','Medium',false,0],['Upload ID or passport','Platform Registration','All','High',true,0],['Upload bank details','Platform Registration','All','High',true,0],['Track approval status for each platform','Platform Registration','All','High',false,0],
['Track weekly income by platform','Tax and Record Keeping','All','High',false,0],['Prepare first provisional tax payment - 31 August','Tax and Record Keeping','All','High',false,0],['Prepare second provisional tax payment - end of February','Tax and Record Keeping','All','High',false,0],['Optional top-up - 30 September','Tax and Record Keeping','All','Medium',false,0],['Prepare annual ITR12 return - editable SARS filing guidance','Tax and Record Keeping','All','High',false,0],['Keep records for 5 years','Tax and Record Keeping','All','High',false,0],
['Android smartphone V6 or newer, V7 recommended','Equipment Checklist','All','High',false,3500],['Data plan','Equipment Checklist','All','High',false,250],['Car phone mount','Equipment Checklist','All','Medium',false,180],['Power bank','Equipment Checklist','All','Medium',false,350],['Cool bag or insulated container','Equipment Checklist','Mr D','High',false,450],['First aid kit','Equipment Checklist','All','Medium',false,250],['Fire extinguisher','Equipment Checklist','Uber passengers','Medium',false,350],
['Install all platform apps','Multi-App Strategy','All','High',false,0],['Learn busy times in local area','Multi-App Strategy','All','Medium',false,0],['Track peak times for 2 weeks','Multi-App Strategy','All','Medium',false,0],['Join local driver groups','Multi-App Strategy','All','Low',false,0],['Create safety rules for app switching','Multi-App Strategy','All','High',false,0]
] as const;
export const documents=['SA ID or passport','Driver licence','PrDP or PDP','Proof of address','Bank confirmation letter','Vehicle RC1','Certificate of roadworthiness','Vehicle licence disc','Operating card or double disc','Insurance confirmation','Passenger liability insurance confirmation','DEKRA or vehicle inspection certificate','Fingerprint results','Profile photo','SARS income tax registration','Provisional tax registration'];
export const costs=['PrDP application','Roadworthy certificate','Comprehensive insurance first month','Android smartphone','Data bundle','Cool bag','Phone mount','Power bank','Vehicle inspection','Fuel float'];
export const articles=['What it means to work as an independent contractor','Sole proprietor basics in South Africa','Why SARS registration matters','What provisional tax means','Why PrDP matters for passengers','Difference between delivery work and passenger transport','How to compare Mr D, Bolt, Uber Eats, and Uber passengers','How to track income and expenses','How to avoid common mistakes','How to protect ratings','Safety tips for drivers','Multi-app strategy tips'];
